---
global:
  copytoram: true
  dostartx: false

autorun:
  ar_disable: false
  ar_nowait: false
  ar_nodel: true
  exec:
    "900 wipe all drives":
      path: "/run/archiso/bootmnt/autorun/wipe_all_drives"
      wait: "always"
