#!/bin/bash

# PREP
DEBUG=0
LOGFILE=/var/log/wipe_shred.log


# FUNCTIONS
function logr {
  logger -t SRCD -p local4.info "$*"
  echo "$*"
  echo "$*" >> "$LOGFILE"
}


wipe_device() {
  local _full_path_to_device="$1"
  local _action=shred
  local _parms=( "--iterations=1" "--force" "--zero" )
  [[ $DEBUG -eq 1 ]] && _action='echo'
  logr "$(date) START $_full_path_to_device"
  logr "$_action ${_parms[@]} $_full_path_to_device"
  set -x
  $_action "${_parms[@]}" "$_full_path_to_device"
  local _rc=$?
  set +x
  logr "$(date) END $_full_path_to_device"
  return "$_rc"
}


# DO WORK

devices=( $( ls /dev/disk/by-id | grep wwn | grep -v -- '-part' ) )
for devID in "${devices[@]}"; do
  wipe_device "/dev/disk/by-id/$devID" || logr "...failed"
done

logr "Devices wiped in ${SECONDS} seconds"

exit 0
